=== apache/attic-stratos/components/org.apache.stratos.manager.console/console/controllers/forms/schema/applications/applicationpolicies.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "root",
    "type": "object",
    "title": "Application Policy Definition",
    "name": "Application Policy",
    "options": {
        "disable_properties": true,
        "disable_collapse": true
    },
    "properties": {
        "id": {
            "id": "root/id",
            "type": "string"
        },
        "algorithm": {
            "id": "root/algorithm",
            "type": "string"
        },
        "networkPartitions": {
            "id": "root/networkPartitions",
            "type": "array",
            "items": {
                "id": "root/networkPartitions/0",
                "type": "string"
            }
        },
        "properties": {
            "id": "root/properties",
            "type": "array",
            "items": [
                {
                    "id": "root/properties/0",
                    "type": "object",
                    "properties": {
                        "name": {
                            "id": "root/properties/0/name",
                            "type": "string"
                        },
                        "value": {
                            "id": "root/properties/0/value",
                            "type": "string"
                        }
                    }
                },
                {
                    "id": "root/properties/1",
                    "type": "object",
                    "properties": {
                        "name": {
                            "id": "root/properties/1/name",
                            "type": "string"
                        },
                        "value": {
                            "id": "root/properties/1/value",
                            "type": "string"
                        }
                    }
                }
            ]
        }
    },
    "required": [
        "id",
        "algorithm",
        "networkPartitions",
        "properties"
    ]
}

=== apache/attic-stratos/products/stratos/modules/integration/src/test/resources/application-bursting-test/application-policies/application-policy-3.json
{
    "id": "application-policy-3",
    "algorithm": "one-after-another",
    "networkPartitions": [
        "network-partition-9",
        "network-partition-10"
    ],
    "properties": [
        {
            "name": "networkPartitionGroups",
            "value": "network-partition-9|network-partition-10"
        },
        {
            "name": "key-2",
            "value": "value-2"
        }
    ]
}
