<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gceConfiguration [
        <!ELEMENT gceConfiguration (cepStatsPublisher|iaasProperties|healthCheckProperties|operationTimeout|namePrefix|log4jPropertiesFileName)*>
        <!ELEMENT cepStatsPublisher (thriftReceiverIp|thriftReceiverPort)*>
        <!ATTLIST cepStatsPublisher
                enable CDATA #REQUIRED>
        <!ELEMENT thriftReceiverIp (#PCDATA)>
        <!ELEMENT thriftReceiverPort (#PCDATA)>
        <!ELEMENT iaasProperties (projectName|projectId|regionName|keyFilePath|gceAccountId|networkName)*>
        <!ELEMENT projectName (#PCDATA)>
        <!ELEMENT projectId (#PCDATA)>
        <!ELEMENT regionName (#PCDATA)>
        <!ELEMENT keyFilePath (#PCDATA)>
        <!ELEMENT gceAccountId (#PCDATA)>
        <!ELEMENT networkName (#PCDATA)>
        <!ELEMENT healthCheckProperties (healthCheckRequestPath|healthCheckPort|healthCheckTimeoutSec|healthCheckIntervalSec|healthCheckUnhealthyThreshold|healthCheckHealthyThreshold)*>
        <!ELEMENT healthCheckRequestPath (#PCDATA)>
        <!ELEMENT healthCheckPort (#PCDATA)>
        <!ELEMENT healthCheckTimeoutSec (#PCDATA)>
        <!ELEMENT healthCheckIntervalSec (#PCDATA)>
        <!ELEMENT healthCheckUnhealthyThreshold (#PCDATA)>
        <!ELEMENT healthCheckHealthyThreshold (#PCDATA)>
        <!ELEMENT operationTimeout (#PCDATA)>
        <!ELEMENT namePrefix (#PCDATA)>
        <!ELEMENT log4jPropertiesFileName (#PCDATA)>
        ]>
<gceConfiguration>

    <cepStatsPublisher enable="false">
        <thriftReceiverIp>127.0.0.1</thriftReceiverIp>
        <thriftReceiverPort>7615</thriftReceiverPort>
    </cepStatsPublisher>

    <iaasProperties>
        <projectName>MyFirstProject</projectName>
        <projectId>gold-access-96509</projectId>
        <regionName>europe-west1</regionName>
        <keyFilePath>/home/sanjaya/keys/p12key-donwloaded.p12</keyFilePath>
        <gceAccountId>164588286821-a517i85433f83e0nthc4qjmoupri394q@developer.gserviceaccount.com</gceAccountId>
        <networkName>default</networkName>
    </iaasProperties>

    <healthCheckProperties>
        <healthCheckRequestPath>/</healthCheckRequestPath>
        <healthCheckPort>80</healthCheckPort>
        <healthCheckTimeoutSec>2</healthCheckTimeoutSec>
        <healthCheckIntervalSec>5</healthCheckIntervalSec>
        <healthCheckUnhealthyThreshold>2</healthCheckUnhealthyThreshold>
        <healthCheckHealthyThreshold>2</healthCheckHealthyThreshold>
    </healthCheckProperties>

    <operationTimeout>10000</operationTimeout>
    <namePrefix>lb</namePrefix>

    <log4jPropertiesFileName>log4j.properties</log4jPropertiesFileName>

</gceConfiguration>